Makefile:关闭minify ，原因： echart.js这个library不知道为何，添加他的源码的时候反而会出错（require出错），目测我使用姿势不对(我已经使用过各种姿势)，暂时关闭minify，迟点在了解； 故而，我放的是他的压缩代码，问题也来，正因为这是压缩，导致concat/sprite任务执行时挂掉了。
报错信息如下:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EACCES, open '/Users/jayin/Desktop/html5slide/dist/static/script/lib/echarts/main.js'

make: *** [main] Error 8